business:
  image: business
  hostname: business
  container_name: business
  ports:
    - target: 8001
      host_ip: 127.0.0.1
      published: 8001
      protocol: tcp
      mode: host
  volumes:
    - "/apps/chat_app_service/business:/apps/chat_app_service/business"

chatting:
  image: chatting
  hostname: chatting
  container_name: chatting
  ports:
    - target: 9001
      host_ip: 127.0.0.1
      published: 9001
      protocol: tcp
      mode: host

    - target: 58080
      host_ip: 127.0.0.1
      published: 58080
      protocol: tcp
      mode: host
  volumes:
    - "/apps/chat_app_service/chatting:/apps/chat_app_service/chatting"

gateway:
  image: gateway
  hostname: gateway
  container_name: gateway
  ports:
    - target: 8008
      host_ip: 127.0.0.1
      published: 8008
      protocol: tcp
      mode: host
  volumes:
    - "/apps/chat_app_service/gateway:/apps/chat_app_service/gateway"

oauth:
  image: oauth
  hostname: oauth
  container_name: oauth
  ports:
    - target: 8002
      host_ip: 127.0.0.1
      published: 8002
      protocol: tcp
      mode: host
  volumes:
    - "/apps/chat_app_service/oauth:/apps/chat_app_service/oauth"