business:
  image: business
  hostname: business
  container_name: business
  ports:
    - "0.0.0.0:8001:8001"
  volumes:
    - "/apps/chat_app_service/business:/apps/chat_app_service/business"
  mem_limit: 500M
  memswap_limit: 500M
# todo 暂时关闭
#chatting:
#  image: chatting
#  hostname: chatting
#  container_name: chatting
#  ports:
#    - "0.0.0.0:9001:9001"
#    - "0.0.0.0:58080:58080"
#  volumes:
#    - "/apps/chat_app_service/chatting:/apps/chat_app_service/chatting"
#  mem_limit: 300M
#  memswap_limit: 300M

gateway:
  image: gateway
  hostname: gateway
  container_name: gateway
  ports:
    - "0.0.0.0:8008:8008"
  volumes:
    - "/apps/chat_app_service/gateway:/apps/chat_app_service/gateway"
  mem_limit: 500M
  memswap_limit: 500M

oauth:
  image: oauth
  hostname: oauth
  container_name: oauth
  ports:
    - "0.0.0.0:8002:8002"
  volumes:
    - "/apps/chat_app_service/oauth:/apps/chat_app_service/oauth"
  mem_limit: 300M
  memswap_limit: 300M

admin:
  image: admin
  hostname: admin
  container_name: admin
  ports:
    - "0.0.0.0:9110:9110"
  volumes:
    - "/apps/chat_app_service/admin:/apps/chat_app_service/admin"
  mem_limit: 500M
  memswap_limit: 500M