spring:
  datasource:
    url: ${spring.datasource.ip}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        # 支持多个共享 Data Id 的配置，优先级小于extension-configs,自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。Config 有 3 个属性，分别是 dataId, group 以及 refresh
        shared-configs[0]:
          data-id: application-dev.yaml # 配置文件名-Data Id
          group: CHAT_APP_GROUP   # 默认为DEFAULT_GROUP
          refresh: false   # 是否动态刷新，默认为false