spring:
  datasource:
    url: jdbc:mysql://47.97.112.114:3306/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789,.
    driver-class-name: com.mysql.cj.jdbc.Driver