spring:
  datasource:
    url: jdbc:mysql://${spring.datasource.ip}/user-center
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
  cloud:
    nacos:
      discovery:
        ip: hub.tensua.com
upload:
  file:
    path: /data/file/images
secure:
  ignore:
    urls: #配置白名单路径,该白名单用来验证是否需要通过token认证，仍然需要gateway验证
      - "/users/register"
      - "/upload"