spring:
  datasource:
    url: jdbc:mysql://${spring.datasource.ip}/user-center
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
upload:
  file:
    path: /data/file/images