spring:
  datasource:
    url: jdbc:mysql://${spring.datasource.ip}/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
webSocket:
  netty:
    port: 58080
    path: /webSocket
    maxContentLength: 8192