spring:
  datasource:
    url: ${spring.datasource.ip}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        ip: hub.tensua.com
webSocket:
  netty:
    port: 58080
    path: /webSocket
    maxContentLength: 8192